const CONSTANTS = {
  entity: {
    accounts: 1,
    contacts: 2,
    opportunities: 3,
    products: 4,
    users: 12,
    // ACTIVITIES: 5,
    // REPORTS: 9,
    // OFERTAS: 10,
    // DOCUMENTS: 11,
    // RELATIONS: 13,
    // ROUTES: 14,
    // ROUTES_EMPRESA: 15,
    // AGENDA: 16,
    // AGENDA_TASK: 160,
    // SURVEY: 17,
    // SURVEYREPORTED: 18,
    // DOCUMENTLIBRARY: 19,
    // NOTIFICATIONS: 20,
    // FAST_CHECKIN: 21,
    // DIRECT_ACCESS_ALTA_PROSPECTO: 22,
    // DIRECT_ACCESS_ALTA_FACIL: 23,
    // FOLDERS_PIPELINE: 24,
    // ORDERS: 25,
    // ORDER_PRODUCTS: 26,
    // L_OFERTAS: 27,
    // ENTITY_DOCUMENTS: 28,
    // SOAP_CACHE: 29,
    // SALES_ORDERS: 31,
    // L_SALES_ORDERS: 32,
    // RATES2: 33,
    // RATES_PRODUCT: 34,
    // ID_ENTITY_FORMS: 35,
    // RATES: 36, // not used
    // SYNC_ERRORS: 37,
    // PHONE_CALL: 38,
    // ID_ADDRESS: 39,
    // ID_BILLBOARD: 40,
    // ID_NPS: 41,
    // PHONE_NUMBER: 42,
    // ID_CAMPAIGNS: 43,
    // ID_GOALS: 44,
  },
  entityId: {
    accountId: 1,
    contactId: 2,
    opportunityId: 3,
    productId: 4,
    userId: 12,
  },
};

export default CONSTANTS;
